/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef CODE_GEN_BY_CSV_CONFIG_HEAD_H_H_HHHH
#define CODE_GEN_BY_CSV_CONFIG_HEAD_H_H_HHHH

#include "ConfigStruct.h"
#include <map>
using namespace std;

class CHeroQualityUpTest {
    static const char* FILE_NAME;
public:
    CHeroQualityUpTest() { };
    ~CHeroQualityUpTest() { };

    int Load(const char* szDir);
    void Clear() { m_mapContent.clear(); }
    int Print() const;
    const SHeroQualityUpTest* Find( int  id) const;
private:
    map<int, SHeroQualityUpTest> m_mapContent;
};
class CVipLevelTest {
    static const char* FILE_NAME;
public:
    CVipLevelTest() { };
    ~CVipLevelTest() { };

    int Load(const char* szDir);
    void Clear() { m_mapContent.clear(); }
    int Print() const;
    const SVipLevelTest* Find( int  id) const;
private:
    map<int, SVipLevelTest> m_mapContent;
};


#endif /* CODE_GEN_BY_CSV_CONFIG_HEAD_H_H_HHHH */