/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef CODE_GEN_BY_CSV_CONFIG_STRUCT_H_H_HHHH
#define CODE_GEN_BY_CSV_CONFIG_STRUCT_H_H_HHHH

/*   Define c types.   */
#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
    #include <stddef.h>
    #include <time.h>
    #include <sys/types.h>

    #if !defined(_WIN32) && !defined(_WIN64)

        #include <stdint.h>
        #include <inttypes.h>

    #else /*if !defined(_WIN32) && !defined(_WIN64)*/

        //The stdint declaras
        typedef  signed char  int8_t;
        typedef  short int16_t;
        typedef  int   int32_t;
        typedef unsigned char  uint8_t;
        typedef unsigned short uint16_t;
        typedef unsigned int   uint32_t;
        #if _MSC_VER >= 1300
            typedef unsigned long long 	uint64_t;
            typedef long long 	int64_t;
        #else /* _MSC_VER */
            typedef unsigned __int64	uint64_t;
            typedef __int64	int64_t;
        #endif /* _MSC_VER */

    #endif /*if !defined(_WIN32) && !defined(_WIN64)*/

    typedef int64_t tdr_longlong;
    typedef uint64_t tdr_ulonglong;
    typedef uint16_t tdr_wchar_t;  /**<Wchar基本数据类型*/
    typedef uint32_t tdr_date_t;	/**<data基本数据类型*/
    typedef uint32_t tdr_time_t;	/**<time基本数据类型*/
    typedef uint64_t tdr_datetime_t; /**<datetime基本数据类型*/
    typedef uint32_t tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/

/*   Define structs/unions.   */
#pragma pack(1)
#include<string>
using std::string;

struct SCFG_SJScene
{
	int		SceneLevel;//场次级别
	string		SceneName;//级别说明
	int		AutoStart;//是否自动开始
	int		TicketFee;//门票
	int		MinCoin;//最少金币限制
	int		MaxCoin;//最大金币限制
	int		BaseCoin;//金币基数
	int		EscapeShapreRate;//逃跑分享比例
	int		MaxLose;//最多输钱
	int		EnableDouble;//是否允许加倍
	int		DoubleLimit;//加倍限制
	int		BaseMulity;//基础倍数
	int		BaseExp;//经验值
	int		GameType;//玩法类型
	int		MatchGame;//赛事类型
	int		FirstGiveTime;//首次出牌时间
	int		GiveTime;//普通出牌时间
	int		LogFlag;//调试日志开关
	int		ErrLogFlag;//错误日志开关
	string		LogPath;//日志文件
	string		RobotCfg;//机器人

};
struct SCFG_VipLevelTest
{
	int		id1;//索引ID1
	string		id2;//索引ID2
	int		id3;//索引ID3
	string		id4;//索引ID4
	string		id6;//索引ID6

};
struct SCFG_VipLevelTest2
{
	int		id1;//索引ID1
	string		id2;//索引ID2
	int		id3;//索引ID3
	string		id4;//索引ID4
	string		id6;//索引ID6

};


#pragma pack()


#endif /* CODE_GEN_BY_CSV_CONFIG_STRUCT_H_H_HHHH */
