/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#ifndef CODE_GEN_BY_CSV_CONFIG_STRUCT_H_H_HHHH
#define CODE_GEN_BY_CSV_CONFIG_STRUCT_H_H_HHHH

/*   Define c types.   */
#ifndef TDR_CUSTOM_C_TYPES
#define TDR_CUSTOM_C_TYPES
    #include <stddef.h>
    #include <time.h>
    #include <sys/types.h>

    #if !defined(_WIN32) && !defined(_WIN64)

        #include <stdint.h>
        #include <inttypes.h>

    #else /*if !defined(_WIN32) && !defined(_WIN64)*/

        //The stdint declaras
        typedef  signed char  int8_t;
        typedef  short int16_t;
        typedef  int   int32_t;
        typedef unsigned char  uint8_t;
        typedef unsigned short uint16_t;
        typedef unsigned int   uint32_t;
        #if _MSC_VER >= 1300
            typedef unsigned long long 	uint64_t;
            typedef long long 	int64_t;
        #else /* _MSC_VER */
            typedef unsigned __int64	uint64_t;
            typedef __int64	int64_t;
        #endif /* _MSC_VER */

    #endif /*if !defined(_WIN32) && !defined(_WIN64)*/

    typedef int64_t tdr_longlong;
    typedef uint64_t tdr_ulonglong;
    typedef uint16_t tdr_wchar_t;  /**<Wchar基本数据类型*/
    typedef uint32_t tdr_date_t;	/**<data基本数据类型*/
    typedef uint32_t tdr_time_t;	/**<time基本数据类型*/
    typedef uint64_t tdr_datetime_t; /**<datetime基本数据类型*/
    typedef uint32_t tdr_ip_t;  /**<IPv4数据类型*/
#endif /*TDR_CUSTOM_C_TYPES*/

/*   Define structs/unions.   */
#pragma pack(1)
#include<string>
using std::string;

struct SCFG_VipLevelTest
{
	int		id1;//索引ID1
	string		id2;//索引ID2
	int		id3;//索引ID3
	string		id4;//索引ID4
	string		id6;//索引ID6

};
struct SCFG_VipLevelTest2
{
	int		id1;//索引ID1
	string		id2;//索引ID2
	int		id3;//索引ID3
	string		id4;//索引ID4
	string		id6;//索引ID6

};


#pragma pack()


#endif /* CODE_GEN_BY_CSV_CONFIG_STRUCT_H_H_HHHH */
