/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

namespace CSVGenCode {
    public class ConfigMgr : Singleton<ConfigMgr> {
        public string CurReadPath = "";
        public string CFG_CSV_DIR = "../../../../../CSV";
        public string ExceptionMsg = "";
        public ECSVReadResult LoadAll() {
            try {
                ECSVReadResult iRet = ECSVReadResult.Succ;
                var dir = Path.Combine(Environment.CurrentDirectory, CFG_CSV_DIR);
                CurReadPath = Path.Combine(dir, "SJScene.csv");
                iRet = m_SJScene.Load(CurReadPath);
                if (iRet != ECSVReadResult.Succ)  return iRet;
                CurReadPath = Path.Combine(dir, "vip_level_test.csv");
                iRet = m_VipLevelTest.Load(CurReadPath);
                if (iRet != ECSVReadResult.Succ)  return iRet;
                CurReadPath = Path.Combine(dir, "vip_level_test2.csv");
                iRet = m_VipLevelTest2.Load(CurReadPath);
                if (iRet != ECSVReadResult.Succ)  return iRet;

                return ECSVReadResult.Succ;
            } catch (Exception e) {
                ExceptionMsg = e.Message;
                return ECSVReadResult.FailedUnkonw;
            }
        }
        public string PrintAll() {
            StringBuilder sb = new StringBuilder();
            m_SJScene.ToString(sb);
            m_VipLevelTest.ToString(sb);
            m_VipLevelTest2.ToString(sb);

            return sb.ToString();
        }
        public ECSVReadResult Reload() { return LoadAll(); }
        public CCFG_SJScene m_SJScene = new CCFG_SJScene();
        public CCFG_VipLevelTest m_VipLevelTest = new CCFG_VipLevelTest();
        public CCFG_VipLevelTest2 m_VipLevelTest2 = new CCFG_VipLevelTest2();

    };
}
