/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/
using System.Text;

namespace CSVGenCode {
    public class SCFG_SJScene //SCFG_SJScene
    {
        public uint      SceneLevel;//场次级别
        public string      SceneName;//级别说明
        public uint      AutoStart;//是否自动开始
        public uint      TicketFee;//门票
        public uint      MinCoin;//最少金币限制
        public uint      MaxCoin;//最大金币限制
        public uint      BaseCoin;//金币基数
        public uint      EscapeShapreRate;//逃跑分享比例
        public uint      MaxLose;//最多输钱
        public uint      EnableDouble;//是否允许加倍
        public uint      DoubleLimit;//加倍限制
        public uint      BaseMulity;//基础倍数
        public uint      BaseExp;//经验值
        public uint      GameType;//玩法类型
        public uint      MatchGame;//赛事类型
        public uint      FirstGiveTime;//首次出牌时间
        public uint      GiveTime;//普通出牌时间
        public uint      LogFlag;//调试日志开关
        public uint      ErrLogFlag;//错误日志开关
        public string      LogPath;//日志文件
        public string      RobotCfg;//机器人


        public override string ToString() {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("SceneLevel = " + SceneLevel);
            sb.AppendLine("SceneName = " + SceneName);
            sb.AppendLine("AutoStart = " + AutoStart);
            sb.AppendLine("TicketFee = " + TicketFee);
            sb.AppendLine("MinCoin = " + MinCoin);
            sb.AppendLine("MaxCoin = " + MaxCoin);
            sb.AppendLine("BaseCoin = " + BaseCoin);
            sb.AppendLine("EscapeShapreRate = " + EscapeShapreRate);
            sb.AppendLine("MaxLose = " + MaxLose);
            sb.AppendLine("EnableDouble = " + EnableDouble);
            sb.AppendLine("DoubleLimit = " + DoubleLimit);
            sb.AppendLine("BaseMulity = " + BaseMulity);
            sb.AppendLine("BaseExp = " + BaseExp);
            sb.AppendLine("GameType = " + GameType);
            sb.AppendLine("MatchGame = " + MatchGame);
            sb.AppendLine("FirstGiveTime = " + FirstGiveTime);
            sb.AppendLine("GiveTime = " + GiveTime);
            sb.AppendLine("LogFlag = " + LogFlag);
            sb.AppendLine("ErrLogFlag = " + ErrLogFlag);
            sb.AppendLine("LogPath = " + LogPath);
            sb.AppendLine("RobotCfg = " + RobotCfg);

            return sb.ToString();
        }
    }
    public class SCFG_VipLevelTest //SCFG_VipLevelTest
    {
        public int      id1;//索引ID1
        public string      id2;//索引ID2
        public int      id3;//索引ID3
        public string      id4;//索引ID4
        public string      id6;//索引ID6


        public override string ToString() {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("id1 = " + id1);
            sb.AppendLine("id2 = " + id2);
            sb.AppendLine("id3 = " + id3);
            sb.AppendLine("id4 = " + id4);
            sb.AppendLine("id6 = " + id6);

            return sb.ToString();
        }
    }
    public class SCFG_VipLevelTest2 //SCFG_VipLevelTest2
    {
        public int      id1;//索引ID1
        public string      id2;//索引ID2
        public int      id3;//索引ID3
        public string      id4;//索引ID4
        public string      id6;//索引ID6


        public override string ToString() {
            StringBuilder sb = new StringBuilder();
            sb.AppendLine("id1 = " + id1);
            sb.AppendLine("id2 = " + id2);
            sb.AppendLine("id3 = " + id3);
            sb.AppendLine("id4 = " + id4);
            sb.AppendLine("id6 = " + id6);

            return sb.ToString();
        }
    }

}

