/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/

#include "ConfigMgr.h"

#if _WIN32 || _WIN64
const char* CConfigMgr::CFG_CSV_DIR = "../../../Config/SO/csv";
#else
const char* CConfigMgr::CFG_CSV_DIR = "../../105/cfg/csv";
#endif

string CConfigMgr::ErrorFileName;
int CConfigMgr::LoadAll()
{
	int iRet = 0;
#Begin_Replace_Tag_Class
	ErrorFileName = "#FileName";
	iRet = m_st#FileName.Load(CFG_CSV_DIR);
	SO_CFG_RT_IF_NOT_ZERO(m_st#FileName.Load, -1);
#End_Replace_Tag_Class
	return 0;
}


int CConfigMgr::Reload()
{
	//return LoadAll();
    return 0;
}

void CConfigMgr::PrintAll()
{
#Begin_Replace_Tag_Class
	m_st#FileName.Print();
#End_Replace_Tag_Class
}


