/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/
using System.Text;

namespace CSVGenCode {
#Begin_Replace_Tag_Class
    public class #StructName //#StructName
    {
#Begin_Replace_Tag_Attri
        public #AttriTypeName      #AttriName;//#AttriCommment
#End_Replace_Tag_Attri

        public override string ToString() {
            StringBuilder sb = new StringBuilder();
#Begin_Replace_Tag_Attri
            sb.AppendLine("#AttriName = " + #AttriName);
#End_Replace_Tag_Attri
            return sb.ToString();
        }
    }
#End_Replace_Tag_Class
}

