/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
********************************************************************/
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.IO;

namespace CSVGenCode {
    public class ConfigMgr : Singleton<ConfigMgr> {
        public string CurReadPath = "";
        public string CFG_CSV_DIR = "../../../../../CSV";
        public string ExceptionMsg = "";
        public ECSVReadResult LoadAll() {
            try {
                ECSVReadResult iRet = ECSVReadResult.Succ;
                var dir = Path.Combine(Environment.CurrentDirectory, CFG_CSV_DIR);
#Begin_Replace_Tag_Class
                CurReadPath = Path.Combine(dir, "#RawFileName.csv");
                iRet = m_#FileName.Load(CurReadPath);
                if (iRet != ECSVReadResult.Succ)  return iRet;
#End_Replace_Tag_Class
                return ECSVReadResult.Succ;
            } catch (Exception e) {
                ExceptionMsg = e.Message;
                return ECSVReadResult.FailedUnkonw;
            }
        }
        public string PrintAll() {
            StringBuilder sb = new StringBuilder();
#Begin_Replace_Tag_Class
            m_#FileName.ToString(sb);
#End_Replace_Tag_Class
            return sb.ToString();
        }
        public ECSVReadResult Reload() { return LoadAll(); }
#Begin_Replace_Tag_Class
        public #ClsName m_#FileName = new #ClsName();
#End_Replace_Tag_Class
    };
}
